### ISSUE TITLE
前端萌新学习中

### ISSUE THREAD

**Issue by CoderMonkie** [wencaizhang/gulu#2]
优秀啊！师兄。
我1902期的，不过还没学Vue的课程。
自己之前倒是搞过一个简单项目。
最近有看公开课，
这个组件库，天天被老师在公开课拿来展示。
支持一下。
+Star

**Comment by wencaizhang** [comment]
一起学习，加油～

**Comment by zhaozhig** [comment]
可以啊,师兄,写得真不错,大赞
